server:
  port: ${PORT}
  tomcat:
    max-connections: 10
    threads:
      max: 3
  servlet:
    context-path: "/"
  forward-headers-strategy: framework

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.errormvcautoconfiguration
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      uri: ${DATABASE_URI}
      database: ${DATABASE_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXP}
      refresh-token:
        expiration: ${JWT_REFRESH_EXP}
  swagger:
    server:
      url: ${SWAGGER_SERVER_URL}


logging:
  level:
    root: info


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    metrics:
      enabled: true
