server:
  port: ${PORT}
  servlet:
    context-path: "/"
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      uri: ${DATABASE_URI}
      database: ${DATABASE_NAME}


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXP}
      refresh-token:
        expiration: ${JWT_REFRESH_EXP}
  swagger:
    server:
      url: ${SWAGGER_SERVER_URL}
